apiVersion: apps/v1
kind: Deployment
metadata:
  name: tap-deployment
  labels:
    app: my-app
spec:
  replicas: 2 # The number of pods to run
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: tap
          image: yashsaxena1115/tap  # Replace with your application's Docker image
          ports:
            - containerPort: 80